### ISSUE TITLE
Example config?

### ISSUE THREAD

**Issue by Jay2645** [handyman5/resmed-scraper#1]
Would it be possible to provide an example configuration file? Or at least instructions in the README -- I'm not 100% sure how to find `viewstate` or `exist_token`.

**Comment by handyman5** [comment]
The `exist_token` comes from Exist's own API; you can get one [here](http://developer.exist.io/#simple-token-authentication). I changed the script logic to not attempt to log in via Python anymore. Instead, I captured a login attempt from my browser as a `curl` command and have the script just run that `curl` and scrape its output. I've attached a screenshot of where to do so using Chrome; if you copy that command and paste it into a file named `mycurl` in the same directory as the script, it should work. Let me know if that doesn't do the trick.
![Screen Shot 2020-07-08 at 12 49 37 PM](https://user-images.githubusercontent.com/192126/86963627-b13b0600-c119-11ea-8930-7896efcc7c75.png)

**Comment by fredrikbuchanan** [comment]
Hi. I copied default aspx as cURL and created a empty config.json. 
but i still get errors 
"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
have i missed anything?
mvh
Fredrik Buchanan

**Comment by handyman5** [comment]
An empty file is not valid JSON, which is what that error is saying.

Here's an example `config.json`:

```
{
"viewstate": "",
"email": "",
"password": "",
"exist_token": "<your Exist API token per http://developer.exist.io/#requesting-a-token>"
}
```

The other empty lines are used by bits of code that are no longer active and I haven't bothered to clean them up since I switched to just running `curl`.

**Comment by fredrikbuchanan** [comment]
Ok. Cool will test it out. Thanks

**Comment by fredrikbuchanan** [comment]
ok i have come a bit further
but running in powershell i get:
PS C:\Drift\myair> python .\scrape.py
The command line is too long.
Traceback (most recent call last):
  File "C:\Drift\myair\scrape.py", line 56, in <module>
    scores_script = [x.renderContents() for x in scripts if 'myScores' in x.renderContents()][0]
IndexError: list index out of range

if i try run it on a linux first resolve host and then typeerror: a bytes-like object is requiered, not 'str'

any tips on what could be wrong

**Comment by fredrikbuchanan** [comment]
solved the linux problem so now i have list index out of range on both win and linux

**Comment by xfader2018** [comment]
Can you please write a small how to install manual please? This is so unclear.

**Comment by badreamer** [comment]
Is this script still working now ?
Seems like Resmed has made some changes - I am not able to see the same structure as you while I try to copy the curl command ...
The 'scripts' variable is populated with the JS file names for me, and I do not see a 'myScores' text in any of those JS files ...

**Comment by joverdijk** [comment]
Same for me. Script seems broken it won't read myScores anymore. 

Traceback (most recent call last):
  File "./scrape.py", line 56, in <module>
    scores_script = [x.renderContents() for x in scripts if 'myScores' in x.renderContents()][0]
IndexError: list index out of range

**Comment by prestomation** [comment]
myAir has re-built their US website and it works very differently.

For anyone who is interested:
I have done a similar reverse-engineering of the new page, the code can be found here: https://github.com/prestomation/resmed_myair_sensors/blob/master/custom_components/resmed_myair/myair_client.py

that package is for integration into a home automation system called 'Home Assistant', but that client file will continue to be decoupled such that it can be used outside home assistant

**Comment by xfader2018** [comment]
> myAir has re-built their US website and it works very differently.
> 
> For anyone who is interested: I have done a similar reverse-engineering of the new page, the code can be found here: https://github.com/prestomation/resmed_myair_sensors/blob/master/custom_components/resmed_myair/myair_client.py
> 
> that package is for integration into a home automation system called 'Home Assistant', but that client file will continue to be decoupled such that it can be used outside home assistant

Awesome stuff. Anyway to get this also working for the EU website?
My user/pass is not accepted now as I'm from eu.
